// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKaKy_ZsoaJnM19NvTd2gpIXyrO1lGKPI',
    appId: '1:517842048800:web:05a689c893844649972945',
    messagingSenderId: '517842048800',
    projectId: 'goal-planner-c7cbf',
    authDomain: 'goal-planner-c7cbf.firebaseapp.com',
    storageBucket: 'goal-planner-c7cbf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2zYD7dZ6GZlaUoTwSca0Bdhhhjp8HO_Q',
    appId: '1:517842048800:android:abcde2c6fd7fc49e972945',
    messagingSenderId: '517842048800',
    projectId: 'goal-planner-c7cbf',
    storageBucket: 'goal-planner-c7cbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaJM9dGWymOkw7eOfo-n1-3BgHV-gvhWM',
    appId: '1:517842048800:ios:90588187e73e05f2972945',
    messagingSenderId: '517842048800',
    projectId: 'goal-planner-c7cbf',
    storageBucket: 'goal-planner-c7cbf.firebasestorage.app',
    androidClientId: '517842048800-no27nmpvnuvndcbjj9po318e5jm0mltm.apps.googleusercontent.com',
    iosClientId: '517842048800-qon2mpume9i2pkbt6l9lhaomkhn7hemt.apps.googleusercontent.com',
    iosBundleId: 'com.example.zhasauApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaJM9dGWymOkw7eOfo-n1-3BgHV-gvhWM',
    appId: '1:517842048800:ios:90588187e73e05f2972945',
    messagingSenderId: '517842048800',
    projectId: 'goal-planner-c7cbf',
    storageBucket: 'goal-planner-c7cbf.firebasestorage.app',
    iosBundleId: 'com.example.zhasauApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKaKy_ZsoaJnM19NvTd2gpIXyrO1lGKPI',
    appId: '1:517842048800:web:6b2e38954e8e9233972945',
    messagingSenderId: '517842048800',
    projectId: 'goal-planner-c7cbf',
    authDomain: 'goal-planner-c7cbf.firebaseapp.com',
    storageBucket: 'goal-planner-c7cbf.firebasestorage.app',
  );
}